# Generated by Django 5.2.17 on 2026-09-02 01:38

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('api', '0002_supprime_modele_infrastructure'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Member',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('role', models.CharField(choices=[('founder', 'Fondateur'), ('member', 'Membre')], default='member', max_length=20)),
                ('job_title', models.CharField(blank=True, max_length=100, verbose_name='Poste')),
                ('department', models.CharField(choices=[('direction', 'Direction'), ('commercial', 'Commercial'), ('marketing', 'Marketing'), ('produit', 'Produit'), ('technique', 'Technique'), ('finance', 'Finance'), ('operations', 'Opérations')], default='commercial', max_length=20, verbose_name='Pôle')),
                ('phone', models.CharField(blank=True, max_length=30, verbose_name='Téléphone')),
                ('joined_on', models.DateField(default=django.utils.timezone.localdate, verbose_name="Arrivée dans l'équipe")),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='member', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Membre',
                'verbose_name_plural': 'Membres',
                'ordering': ['user__first_name', 'user__username'],
            },
        ),
        migrations.CreateModel(
            name='MonthlyObjective',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Ramené au premier jour du mois', verbose_name='Mois')),
                ('revenue_target', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='CA attendu')),
                ('revenue_achieved', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='CA réalisé')),
                ('clients_target', models.PositiveIntegerField(default=0, verbose_name='Clients attendus')),
                ('clients_achieved', models.PositiveIntegerField(default=0, verbose_name='Clients signés')),
                ('focus', models.CharField(blank=True, help_text='La priorité du mois en une phrase', max_length=255, verbose_name='Objectif principal')),
                ('notes', models.TextField(blank=True, verbose_name='Commentaire')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('active', 'En cours'), ('closed', 'Clôturé')], default='active', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='objectives', to='api.member')),
            ],
            options={
                'verbose_name': 'Objectif mensuel',
                'verbose_name_plural': 'Objectifs mensuels',
                'ordering': ['-month', 'member__user__first_name'],
            },
        ),
        migrations.CreateModel(
            name='Report',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('period_type', models.CharField(choices=[('daily', 'Journalier'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel')], default='weekly', max_length=20, verbose_name='Périodicité')),
                ('period_start', models.DateField(verbose_name='Début de période')),
                ('period_end', models.DateField(verbose_name='Fin de période')),
                ('summary', models.TextField(verbose_name='Bilan')),
                ('achievements', models.TextField(blank=True, verbose_name='Réalisations')),
                ('blockers', models.TextField(blank=True, verbose_name='Difficultés')),
                ('next_steps', models.TextField(blank=True, verbose_name='Prochaines étapes')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('submitted', 'Soumis')], default='draft', max_length=20)),
                ('submitted_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='api.member')),
            ],
            options={
                'verbose_name': 'Rapport',
                'verbose_name_plural': 'Rapports',
                'ordering': ['-period_end', '-created_at'],
            },
        ),
        migrations.CreateModel(
            name='RoadmapItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200, verbose_name='Jalon')),
                ('description', models.TextField(blank=True)),
                ('due_date', models.DateField(blank=True, null=True, verbose_name='Échéance')),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('done', 'Terminé'), ('blocked', 'Bloqué')], default='todo', max_length=20)),
                ('progress', models.PositiveSmallIntegerField(default=0, validators=[django.core.validators.MinValueValidator(0), django.core.validators.MaxValueValidator(100)], verbose_name='Avancement (%)')),
                ('position', models.PositiveSmallIntegerField(default=0, verbose_name='Ordre')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('objective', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='roadmap', to='api.monthlyobjective')),
            ],
            options={
                'verbose_name': 'Jalon de feuille de route',
                'verbose_name_plural': 'Feuille de route',
                'ordering': ['position', 'due_date', 'id'],
            },
        ),
        migrations.CreateModel(
            name='DailyTask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Jour')),
                ('title', models.CharField(max_length=200, verbose_name='Tâche')),
                ('description', models.TextField(blank=True)),
                ('status', models.CharField(choices=[('todo', 'À faire'), ('in_progress', 'En cours'), ('done', 'Terminée'), ('blocked', 'Bloquée')], default='todo', max_length=20)),
                ('priority', models.PositiveSmallIntegerField(choices=[(1, 'Basse'), (2, 'Normale'), (3, 'Haute'), (4, 'Urgente')], default=2)),
                ('estimated_minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Durée estimée (min)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tasks', to='api.member')),
                ('roadmap_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tasks', to='api.roadmapitem')),
            ],
            options={
                'verbose_name': 'Tâche du jour',
                'verbose_name_plural': 'Tâches du jour',
                'ordering': ['-date', '-priority', 'id'],
            },
        ),
        migrations.AddIndex(
            model_name='monthlyobjective',
            index=models.Index(fields=['-month'], name='api_objective_month_idx'),
        ),
        migrations.AddIndex(
            model_name='monthlyobjective',
            index=models.Index(fields=['member', '-month'], name='api_objective_member_idx'),
        ),
        migrations.AddConstraint(
            model_name='monthlyobjective',
            constraint=models.UniqueConstraint(fields=('member', 'month'), name='unique_objective_per_member_month'),
        ),
        migrations.AddIndex(
            model_name='report',
            index=models.Index(fields=['member', '-period_end'], name='api_report_member_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytask',
            index=models.Index(fields=['member', '-date'], name='api_task_member_date_idx'),
        ),
        migrations.AddIndex(
            model_name='dailytask',
            index=models.Index(fields=['-date'], name='api_task_date_idx'),
        ),
    ]
