# Generated by Django 5.2.17 on 2026-09-02 13:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0004_profils_comptes_existants'),
    ]

    operations = [
        migrations.AddField(
            model_name='report',
            name='decisions',
            field=models.TextField(blank=True, verbose_name='Décisions'),
        ),
        migrations.AddField(
            model_name='report',
            name='location',
            field=models.CharField(blank=True, max_length=200, verbose_name='Lieu'),
        ),
        migrations.AddField(
            model_name='report',
            name='participants',
            field=models.TextField(blank=True, verbose_name='Participants'),
        ),
        migrations.AddField(
            model_name='report',
            name='title',
            field=models.CharField(blank=True, max_length=200, verbose_name='Objet'),
        ),
        migrations.AlterField(
            model_name='report',
            name='period_type',
            field=models.CharField(choices=[('daily', 'Journalier'), ('weekly', 'Hebdomadaire'), ('monthly', 'Mensuel'), ('mission', 'Rapport de mission'), ('meeting', 'Rapport de réunion')], default='weekly', max_length=20, verbose_name='Type de rapport'),
        ),
    ]
