# Generated by Django 5.2.17 on 2026-09-02 14:23

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0005_rapports_mission_et_reunion'),
    ]

    operations = [
        migrations.AlterField(
            model_name='member',
            name='role',
            field=models.CharField(choices=[('founder', 'Fondateur'), ('manager', 'Gérant'), ('member', 'Membre')], default='member', max_length=20),
        ),
        migrations.CreateModel(
            name='Payslip',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('month', models.DateField(help_text='Ramené au premier jour du mois', verbose_name='Mois')),
                ('base_salary', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salaire de base')),
                ('overtime_hours', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=6, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Heures supplémentaires')),
                ('overtime_amount', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Montant des heures supplémentaires')),
                ('bonuses', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Primes')),
                ('deductions', models.DecimalField(decimal_places=2, default=Decimal('0'), help_text='Absences, mises à pied sans solde, avances', max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Retenues')),
                ('contributions', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Cotisations')),
                ('notes', models.TextField(blank=True, verbose_name='Observations')),
                ('status', models.CharField(choices=[('draft', 'Brouillon'), ('issued', 'Émis')], default='draft', max_length=20)),
                ('issued_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payslips', to='api.member')),
            ],
            options={
                'verbose_name': 'Bulletin de paie',
                'verbose_name_plural': 'Bulletins de paie',
                'ordering': ['-month', 'member__user__first_name'],
                'indexes': [models.Index(fields=['-month'], name='api_payslip_month_idx'), models.Index(fields=['member', '-month'], name='api_payslip_member_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'month'), name='unique_payslip_per_member_month')],
            },
        ),
        migrations.CreateModel(
            name='StaffEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('suspension', 'Mise à pied'), ('observation', 'Observation'), ('lateness', 'Retard'), ('overtime', 'Heures supplémentaires')], max_length=20, verbose_name='Nature')),
                ('date', models.DateField(verbose_name='Date')),
                ('end_date', models.DateField(blank=True, help_text="Dernier jour d'une mise à pied", null=True, verbose_name='Fin')),
                ('minutes', models.PositiveIntegerField(blank=True, null=True, verbose_name='Minutes de retard')),
                ('hours', models.DecimalField(blank=True, decimal_places=2, max_digits=6, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Heures supplémentaires')),
                ('is_paid', models.BooleanField(default=False, help_text='Mise à pied rémunérée, ou heures supplémentaires payées', verbose_name='Avec solde')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('decision', models.TextField(blank=True, verbose_name='Suite donnée')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='staff_events', to='api.member')),
                ('recorded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='staff_events_recorded', to='api.member')),
            ],
            options={
                'verbose_name': 'Évènement de personnel',
                'verbose_name_plural': 'Évènements de personnel',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['member', '-date'], name='api_staffevent_member_idx'), models.Index(fields=['kind', '-date'], name='api_staffevent_kind_idx')],
            },
        ),
    ]
