# Generated by Django 5.2.17 on 2026-09-02 20:18

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0006_gerant_paie_et_personnel'),
    ]

    operations = [
        migrations.CreateModel(
            name='Suggestion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(choices=[('idea', 'Idée'), ('problem', 'Problème'), ('question', 'Question')], default='idea', max_length=20, verbose_name='Nature')),
                ('message', models.TextField(verbose_name='Message')),
                ('status', models.CharField(choices=[('new', 'Nouvelle'), ('read', 'Lue'), ('done', 'Traitée')], default='new', max_length=20)),
                ('reply', models.TextField(blank=True, verbose_name='Réponse')),
                ('handled_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='suggestions', to='api.member')),
                ('handled_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='suggestions_handled', to='api.member')),
            ],
            options={
                'verbose_name': 'Suggestion',
                'verbose_name_plural': 'Suggestions',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['status', '-created_at'], name='api_suggestion_idx')],
            },
        ),
    ]
