# Generated by Django 5.2.17 on 2026-09-02 20:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0007_boite_a_suggestions'),
    ]

    operations = [
        migrations.AddField(
            model_name='dailytask',
            name='started_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Démarrée le'),
        ),
    ]
