# Generated by Django 5.2.17 on 2026-09-03 00:04

import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0008_duree_reelle_des_taches'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='base_salary',
            field=models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Salaire de base'),
        ),
        migrations.CreateModel(
            name='Reaction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('objectif', 'Objectif atteint'), ('bravo', 'Bravo'), ('entraide', 'Entraide'), ('initiative', 'Initiative'), ('rappel', "Rappel à l'ordre"), ('manquement', 'Manquement')], max_length=20, verbose_name='Nature')),
                ('points', models.IntegerField(help_text='Négatif pour retirer des points', verbose_name='Points')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Motif')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Date')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('author', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reactions_given', to='api.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='reactions', to='api.member')),
            ],
            options={
                'verbose_name': 'Réaction',
                'verbose_name_plural': 'Réactions',
                'ordering': ['-date', '-created_at'],
                'indexes': [models.Index(fields=['member', '-date'], name='api_reaction_member_idx')],
            },
        ),
    ]
