# Generated by Django 5.2.17 on 2026-09-07 10:36

import datetime
import django.core.validators
import django.db.models.deletion
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0010_bulletin_sans_brouillon'),
    ]

    operations = [
        migrations.AddField(
            model_name='member',
            name='leave_entitlement',
            field=models.PositiveSmallIntegerField(default=18, validators=[django.core.validators.MaxValueValidator(90)], verbose_name='Congés annuels (jours)'),
        ),
        migrations.AddField(
            model_name='member',
            name='work_ends_at',
            field=models.TimeField(default=datetime.time(17, 0), verbose_name='Fin de journée'),
        ),
        migrations.AddField(
            model_name='member',
            name='work_starts_at',
            field=models.TimeField(default=datetime.time(8, 0), verbose_name='Début de journée'),
        ),
        migrations.CreateModel(
            name='Attendance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(default=django.utils.timezone.localdate, verbose_name='Jour')),
                ('check_in', models.DateTimeField(verbose_name='Arrivée')),
                ('check_out', models.DateTimeField(blank=True, null=True, verbose_name='Départ')),
                ('late_minutes', models.PositiveIntegerField(default=0, verbose_name='Retard')),
                ('note', models.CharField(blank=True, max_length=200, verbose_name='Observation')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='attendances', to='api.member')),
            ],
            options={
                'verbose_name': 'Pointage',
                'verbose_name_plural': 'Pointages',
                'ordering': ['-date', '-check_in'],
                'indexes': [models.Index(fields=['member', '-date'], name='api_attendance_member_idx'), models.Index(fields=['-date'], name='api_attendance_date_idx')],
                'constraints': [models.UniqueConstraint(fields=('member', 'date'), name='unique_attendance_per_member_day')],
            },
        ),
        migrations.CreateModel(
            name='LeaveRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('paid', 'Congé payé'), ('unpaid', 'Congé sans solde'), ('sick', 'Maladie'), ('special', 'Absence exceptionnelle')], default='paid', max_length=20, verbose_name='Nature')),
                ('start_date', models.DateField(verbose_name='Premier jour')),
                ('end_date', models.DateField(verbose_name='Dernier jour')),
                ('half_day', models.BooleanField(default=False, help_text='Une seule journée, prise pour moitié', verbose_name='Demi-journée')),
                ('reason', models.TextField(verbose_name='Motif')),
                ('status', models.CharField(choices=[('pending', 'En attente'), ('approved', 'Accordée'), ('refused', 'Refusée'), ('cancelled', 'Annulée')], default='pending', max_length=20)),
                ('decision', models.TextField(blank=True, verbose_name='Réponse')),
                ('decided_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('decided_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leaves_decided', to='api.member')),
                ('member', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='leaves', to='api.member')),
            ],
            options={
                'verbose_name': 'Demande de congé',
                'verbose_name_plural': 'Demandes de congé',
                'ordering': ['-start_date', '-created_at'],
                'indexes': [models.Index(fields=['member', '-start_date'], name='api_leave_member_idx'), models.Index(fields=['status', '-start_date'], name='api_leave_status_idx')],
            },
        ),
    ]
